cc_library(
  name = "test_harness",
  hdrs = [
    "test_harness.h",
    "test_harness_utils.h",
  ],
  srcs = ["test_harness.cc"],
  deps = [
    "//cc/backend/opcode_executor",
    "//external:gtest",
  ],
  visibility = ["//visibility:public"],
)
