cc_library(
  name = "joypad_module",
  hdrs = ["joypad_module.h"],
  deps = [
    "//cc/backend/memory/interrupt:interrupt_flag",
    "//cc/backend/memory:flags",
    "//cc/backend/memory:module",
    "@com_github_google_glog//:glog",
  ],
  visibility = ["//visibility:public"],
)

