/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_turbosanta_backend_sound_NativeAudio */

#ifndef _Included_com_turbosanta_backend_sound_NativeAudio
#define _Included_com_turbosanta_backend_sound_NativeAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_turbosanta_backend_sound_NativeAudio
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_sound_NativeAudio_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
