cc_library(
  name = "timer",
  hdrs = [
    "divider_flag.h",
    "timer_module.h",
  ],
  deps = [
    "//backend/memory:flags",
    "//backend/memory:interrupt_flag",
    "//backend/memory:module",
    "//submodules:glog",
  ],
  visibility = ["//visibility:public"], #"//backend/memory:__pkg__"],
)
