cc_library(
  name = "timer",
  hdrs = [
    "divider_flag.h",
    "timer_module.h",
  ],
  deps = [
    "//cc/backend/memory/interrupt:interrupt_flag",
    "//cc/backend/memory:flags",
    "//cc/backend/memory:module",
    "@com_github_google_glog//:glog",
  ],
  visibility = ["//visibility:public"], #"//cc/backend/memory:__pkg__"],
)
