/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_turbosanta_backend_graphics_Screen */

#ifndef _Included_com_turbosanta_backend_graphics_Screen
#define _Included_com_turbosanta_backend_graphics_Screen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_turbosanta_backend_graphics_Screen
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_graphics_Screen_init
  (JNIEnv *, jobject);

/*
 * Class:     com_turbosanta_backend_graphics_Screen
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_turbosanta_backend_graphics_Screen_getWidth
  (JNIEnv *, jclass);

/*
 * Class:     com_turbosanta_backend_graphics_Screen
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_turbosanta_backend_graphics_Screen_getHeight
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
