/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_turbosanta_backend_Clocktroller */

#ifndef _Included_com_turbosanta_backend_Clocktroller
#define _Included_com_turbosanta_backend_Clocktroller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_turbosanta_backend_Clocktroller
 * Method:    init
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_Clocktroller_init
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_turbosanta_backend_Clocktroller
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_Clocktroller_run
  (JNIEnv *, jobject);

/*
 * Class:     com_turbosanta_backend_Clocktroller
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_Clocktroller_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_turbosanta_backend_Clocktroller
 * Method:    kill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_Clocktroller_kill
  (JNIEnv *, jobject);

/*
 * Class:     com_turbosanta_backend_Clocktroller
 * Method:    waitUntilDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_Clocktroller_waitUntilDone
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
