/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_turbosanta_backend_clocktroller_Clocktroller */

#ifndef _Included_com_turbosanta_backend_clocktroller_Clocktroller
#define _Included_com_turbosanta_backend_clocktroller_Clocktroller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_turbosanta_backend_clocktroller_Clocktroller
 * Method:    init
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_clocktroller_Clocktroller_init
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_turbosanta_backend_clocktroller_Clocktroller
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_clocktroller_Clocktroller_run
  (JNIEnv *, jobject);

/*
 * Class:     com_turbosanta_backend_clocktroller_Clocktroller
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_clocktroller_Clocktroller_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_turbosanta_backend_clocktroller_Clocktroller
 * Method:    kill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_clocktroller_Clocktroller_kill
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
