cc_library(
  name = "unimplemented_module",
  hdrs = ["unimplemented_module.h"],
  deps = [
    "//cc/backend/memory:flags",
    "//cc/backend/memory:module",
    "@com_github_google_glog//:glog",
  ],
  visibility = ["//visibility:public"],
)

