cc_library(
  name = "dma_transfer",
  hdrs = ["dma_transfer.h"],
  deps = [
    "//cc/backend/memory:flags",
    "//cc/backend/memory:memory_mapper",
    "//cc/backend/memory:module",
  ],
  visibility = ["//visibility:public"],
)
