new_git_repository(
  name = "remote_gtest",
  remote = "https://github.com/bjh83/googletest.git",
  commit = "7c508e6611f14cbc0da048c0e726870b93b1cc00",
  build_file = "external_build_files/gtest.BUILD",
)

bind(
  name = "gtest",
  actual = "@remote_gtest//:main",
)

new_git_repository(
  name = "remote_glog",
  remote = "https://github.com/google/glog.git",
  commit = "47ab571f38e8c6266c260010ac631f888e302e6d",
  build_file = "external_build_files/glog.BUILD",
)

bind(
  name = "glog",
  actual = "@remote_glog//:main",
)

git_repository(
  name = "remote_protobuf",
  remote = "https://github.com/google/protobuf.git",
  commit = "c9418912cb5483551fecde5463c56a0ae40830fb",
)

bind(
  name = "protoc",
  actual = "@remote_protobuf//:protoc"
)

bind(
  name = "protobuf_clib",
  actual = "@remote_protobuf//:protobuf",
)

bind(
  name = "protobuf",
  actual = "//third_party:protobuf",
)

maven_jar(
  name = "remote_guava",
  artifact = "com.google.guava:guava:18.0",
  sha1 = "cce0823396aa693798f8882e64213b1772032b09",
)

bind(
  name = "guava",
  actual = "@remote_guava//jar"
)

maven_jar(
  name = "remote_findbugs",
  artifact = "com.google.code.findbugs:jsr305:3.0.0",
  sha1 = "5871fb60dc68d67da54a663c3fd636a10a532948",
)

bind(
  name = "findbugs",
  actual = "@remote_findbugs//jar",
)
