cc_library(
  name = "sound_controller",
  srcs = ["sound_controller.cc"],
  hdrs = ["sound_controller.h"],
  deps = [
    "//cc/backend/memory:memory_segment",
    "//cc/backend/memory:module",
  ],
  visibility = ["//visibility:public"],
)