/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_turbosanta_backend_logging_MessageController */

#ifndef _Included_com_turbosanta_backend_logging_MessageController
#define _Included_com_turbosanta_backend_logging_MessageController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_turbosanta_backend_logging_MessageController
 * Method:    getCommunicationLayerPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_turbosanta_backend_logging_MessageController_getCommunicationLayerPointer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
