/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_turbosanta_backend_logging_CommunicationLayer */

#ifndef _Included_com_turbosanta_backend_logging_CommunicationLayer
#define _Included_com_turbosanta_backend_logging_CommunicationLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_turbosanta_backend_logging_CommunicationLayer
 * Method:    takeMessageInternal
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_turbosanta_backend_logging_CommunicationLayer_takeMessageInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_turbosanta_backend_logging_CommunicationLayer
 * Method:    isClosed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_turbosanta_backend_logging_CommunicationLayer_isClosed
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
