/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_turbosanta_backend_joypad_Joypad */

#ifndef _Included_com_turbosanta_backend_joypad_Joypad
#define _Included_com_turbosanta_backend_joypad_Joypad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_turbosanta_backend_joypad_Joypad
 * Method:    init
 * Signature: (Lcom/turbosanta/backend/clocktroller/Clocktroller;)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_joypad_Joypad_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_turbosanta_backend_joypad_Joypad
 * Method:    setDown
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_joypad_Joypad_setDown
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_turbosanta_backend_joypad_Joypad
 * Method:    setUp
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_joypad_Joypad_setUp
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_turbosanta_backend_joypad_Joypad
 * Method:    setLeft
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_joypad_Joypad_setLeft
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_turbosanta_backend_joypad_Joypad
 * Method:    setRight
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_joypad_Joypad_setRight
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_turbosanta_backend_joypad_Joypad
 * Method:    setStart
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_joypad_Joypad_setStart
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_turbosanta_backend_joypad_Joypad
 * Method:    setSelect
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_joypad_Joypad_setSelect
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_turbosanta_backend_joypad_Joypad
 * Method:    setB
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_joypad_Joypad_setB
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_turbosanta_backend_joypad_Joypad
 * Method:    setA
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_turbosanta_backend_joypad_Joypad_setA
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
